# Change these first
owner: jparga # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 * * * *"

sites:
#  - name: DemosMF   # Consume 0.8€ día
#    url: https://demos.marcafranca.com/
  - name: MEREBA
    url: https://www.mereba.com
  - name: Test Mereba
    url: https://mereba.com.es
  - name: Marca Franca
    url: https://marcafranca.com
  - name: Canal Responsable Web
    url: https://canalresponsable.com
  - name: MFREG
    url: https://mfreg.marcafranca.com/robots.txt
  - name: Atletismo máster
    url: https://atletismomaster.es
  - name: Parga Asociados
    url: https://pargaasociados.es
  #- name: Test Broken Site
  #  url: https://thissitedoesnotexist.koj.co
  #- name: IPv6 test
  #  url: forwardemail.net
  #  port: 80
  #  check: "tcp-ping"
  #  ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime_MEREBA
  introTitle: "**Upptime Mereba** uptime monitor and status page for jparga sites."
  introMessage: Fork of github.com/upptime repository.
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
